/*////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////*/
/*////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////*/

CREATE DATABASE adota_pet;
USE adota_pet;
SHOW TABLES;

/*###############################################################################################################################################*/

/*############################# TABELA USUARIO*/
CREATE TABLE
			ADPET01_USUARIO (
						 ADPET01_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET01_NOME VARCHAR(200) NOT NULL
						,ADPET01_NOME_USUARIO VARCHAR(100) NOT NULL
						,ADPET01_ID_PERFIL_USUARIO BIGINT NOT NULL
						,ADPET01_ID_CLIENTE BIGINT 
						,ADPET01_DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
						,ADPET01_DATA_LANCAMENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
						,ADPET01_ATIVO CHAR(1) NOT NULL
						 )ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET01_USUARIO;

/*############################# TABELA PERFIL USUÁRIO*/
CREATE TABLE
			ADPET02_PERFIL_USUARIO (
						 ADPET02_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET02_DESCRICAO VARCHAR(100) NOT NULL 
						,ADPET02_ATIVO CHAR(1) NOT NULL
						 )ENGINE=InnoDB DEFAULT CHARSET=latin1;

DESCRIBE ADPET02_PERFIL_USUARIO;


/*############################# TABELA TIPO PESSOA CLIENTE*/
CREATE TABLE
			ADPET03_TIPO_PESSOA_CLIENTE (
						 ADPET03_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET03_TIPO CHAR(1)
						,ADPET03_ATIVO CHAR(1)
						)ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET03_TIPO_PESSOA_CLIENTE;	


/*############################# TABELA CLIENTE*/
CREATE TABLE
			ADPET04_CLIENTE (
						 ADPET04_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET04_ID_TIPO_PESSOA BIGINT NOT NULL						
						,ADPET04_NOME VARCHAR(200) NOT NULL
						,ADPET04_CPF VARCHAR(20) 
						,ADPET04_CNPJ VARCHAR(20) 
						,ADPET04_RAZAO_SOCIAL VARCHAR(200) 
						,ADPET04_NOME_FANTASIA VARCHAR(200)
						,ADPET04_IDADE INT 
						,ADPET04_ENDERECO VARCHAR(400) 
						,ADPET04_BAIRRO VARCHAR(200) 
						,ADPET04_CIDADE VARCHAR(200)
						,ADPET04_DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
						,ADPET01_DATA_LANCAMENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
						,ADPET01_ID_USUARIO_LANCAMENTO BIGINT
						,ADPET04_ATIVO CHAR(1) NOT NULL
						)ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET04_CLIENTE;


/*############################# TABELA ANIMAL PET*/
CREATE TABLE
			ADPET05_ANIMAL_PET (
						 ADPET05_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET05_NOME VARCHAR(200) NOT NULL
						,ADPET05_ID_ESPECIE BIGINT NOT NULL
						,ADPET05_ID_RACA BIGINT 
						,ADPET05_PORTE BIGINT 
						,ADPET05_IDADE_ESTIMADA INT 
						,ADPET05_COR_PELAGEM VARCHAR(200) 
						,ADPET05_CADASTRADO CHAR(1) NOT NULL 
						,ADPET05_SINAIS_MARCAS_PARTICULARES VARCHAR(500)
						,ADPET05_DESCRICAO VARCHAR(500)
						,ADPET05_DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
						,ADPET04_ADOTADO CHAR(1) NOT NULL
						)ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET05_ANIMAL_PET;


/*############################# TABELA ESPECIE ANIMAL*/
CREATE TABLE
			ADPET06_ESPECIE (
						 ADPET06_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET06_DESCRICAO VARCHAR(200)
						,ADPET06_ATIVO CHAR(1)
						)ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET06_ESPECIE;


/*############################# TABELA RACA ANIMAL*/
CREATE TABLE
			ADPET07_RACA (
						 ADPET07_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET07_DESCRICAO VARCHAR(200)
						,ADPET07_ID_ESPECIE
						,ADPET07_ATIVO CHAR(1)
						)ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET07_RACA;


/*############################# TABELA ADOCA*/
CREATE TABLE
			ADPET08_LANCAMENTO_ADOCAO (
						 ADPET08_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET08_ID_CLIENTE BIGINT NOT NULL
						,ADPET08_ID_USUARIO_LANCAMENTO BIGINT NOT NULL
						,ADPET08_ID_USUARIO BIGINT NOT NULL
						,ADPET08_DATA_LANCAMENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
						,ADPET08_DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
						)ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET08_LANCAMENTO_ADOCAO;


CREATE TABLE
			ADPET09_MOVIMENTO_ADOCAO (
						 ADPET09_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET09_ID_ANIMAL_PET BIGINT NOT NULL
						,ADPET09_ID_LANCAMENTO_ADOCAO BIGINT NOT NULL
						,ADPET09_ID_USUARIO_LANCAMENTO BIGINT NOT NULL
						,ADPET09_ID_USUARIO BIGINT NOT NULL
						,ADPET09_DATA_LANCAMENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
						,ADPET09_DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
						)ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET09_MOVIMENTO_ADOCAO;


/*############################# TABELA ENDEREÇO*/
CREATE TABLE
			ADPET10_ENDERECO (
						 ADPET10_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET10_DESCRICAO VARCHAR(200)
						,ADPET10_ATIVO CHAR(1)
						)ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET10_ENDERECO;

/*############################# TABELA CONTATO*/

CREATE TABLE
			ADPET11_CONTATO (
						 ADPET10_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
						,ADPET10_TELEFONE VARCHAR(20)
						,ADPET10_EMAIL VARCHAR(100)
						)ENGINE=InnoDB DEFAULT CHARSET=latin1;
DESCRIBE ADPET11_CONTATO;


-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- MODIFICADORES / DECLARACOES CHAVE ESTRANGEIRA

ALTER TABLE ADPET01_USUARIO ADD CONSTRAINT FK_ADPET01_ID_PERFIL_USUARIO_EM_USUARIO_IDX FOREIGN KEY (ADPET01_ID_PERFIL_USUARIO) REFERENCES ADPET02_PERFIL_USUARIO (ADPET02_ID);

/*############################# fazer essa verificação com Ana, sobre adicionar uma referência pra TABELA CLIENTE!!!!*/
-- ALTER TABLE ADPET01_USUARIO ADD ADPET01_ID_CLIENTE BIGINT
ALTER TABLE ADPET01_USUARIO ADD CONSTRAINT FK_ADPET01_ID_CLIENTE_EM_USUARIO_IDX FOREIGN KEY (ADPET01_ID_CLIENTE) REFERENCES ADPET04_CLIENTE (ADPET04_ID);

ALTER TABLE ADPET04_CLIENTE ADD CONSTRAINT FK_ADPET04_ID_TIPO_PESSOA_EM_CLIENTE_IDX FOREIGN KEY (ADPET04_ID_TIPO_PESSOA) REFERENCES ADPET03_TIPO_PESSOA_CLIENTE (ADPET03_ID);
ALTER TABLE ADPET04_CLIENTE ADD CONSTRAINT FK_ADPET04_ID_USUARIO_LANCAMENTO_EM_CLIENTE_IDX FOREIGN KEY (ADPET01_ID_USUARIO_LANCAMENTO) REFERENCES ADPET01_USUARIO (ADPET01_ID);

/*############################# fazer essa verificação com Ana, sobre adicionar uma referência pra TABELA CLIENTE!!!!*/
-- ALTER TABLE ADPET04_CLIENTE ADD ADPET04_ID_USUARIO BIGINT
-- ALTER TABLE ADPET04_CLIENTE ADD CONSTRAINT FK_ADPET04_ID_USUARIO_EM_CLIENTE_IDX FOREIGN KEY (ADPET04_ID_USUARIO) REFERENCES ADPET01_USUARIO (ADPET03_ID);

ALTER TABLE ADPET05_ANIMAL_PET ADD CONSTRAINT FK_ADPET05_ID_ESPECIE_EM_ANIMALPET_IDX FOREIGN KEY (ADPET05_ID_ESPECIE) REFERENCES ADPET06_ESPECIE (ADPET06_ID);
ALTER TABLE ADPET05_ANIMAL_PET ADD CONSTRAINT FK_ADPET05_ID_RACA_EM_ANIMALPET_IDX FOREIGN KEY (ADPET05_ID_RACA) REFERENCES ADPET07_RACA (ADPET07_ID);
ALTER TABLE ADPET07_RACA ADD CONSTRAINT FK_ADPET07_ID_ESPECIE_EM_RACA_IDX FOREIGN KEY (ADPET07_ID_ESPECIE) REFERENCES ADPET06_ESPECIE (ADPET06_ID);



ALTER TABLE ADPET08_LANCAMENTO_ADOCAO ADD CONSTRAINT FK_ADPET08_ID_CLIENTE_EM_LANCAMENTO_DOACAO_IDX FOREIGN KEY (ADPET08_ID_CLIENTE) REFERENCES ADPET04_CLIENTE (ADPET04_ID);
ALTER TABLE ADPET08_LANCAMENTO_ADOCAO ADD CONSTRAINT FK_ADPET08_ID_USUARIO_LANCAMENTO_EM_LANCAMENTO_DOACAO_IDX FOREIGN KEY (ADPET08_ID_USUARIO_LANCAMENTO) REFERENCES ADPET01_USUARIO (ADPET01_ID);
ALTER TABLE ADPET08_LANCAMENTO_ADOCAO ADD CONSTRAINT FK_ADPET08_ID_USUARIO_EM_LANCAMENTO_DOACAO_IDX FOREIGN KEY (ADPET08_ID_USUARIO) REFERENCES ADPET01_USUARIO (ADPET01_ID);

ALTER TABLE ADPET09_MOVIMENTO_ADOCAO ADD CONSTRAINT FK_ADPET09_ID_LANCAMENTO_ADOCAO_EM_MOVIMENTO_DOACAO_IDX FOREIGN KEY (ADPET09_ID_LANCAMENTO_ADOCAO) REFERENCES ADPET08_LANCAMENTO_ADOCAO (ADPET08_ID);
ALTER TABLE ADPET09_MOVIMENTO_ADOCAO ADD CONSTRAINT FK_ADPET09_ID_ANIMALPET_EM_MOVIMENTO_DOACAO_IDX FOREIGN KEY (ADPET09_ID_ANIMAL_PET) REFERENCES ADPET05_ANIMAL_PET (ADPET05_ID);
ALTER TABLE ADPET09_MOVIMENTO_ADOCAO ADD CONSTRAINT FK_ADPET09_ID_USUARIO_MOVIMENTO_EM_LANCAMENTO_DOACAO_IDX FOREIGN KEY (ADPET09_ID_USUARIO_LANCAMENTO) REFERENCES ADPET01_USUARIO (ADPET01_ID);
ALTER TABLE ADPET09_MOVIMENTO_ADOCAO ADD CONSTRAINT FK_ADPET09_ID_USUARIO_EM_MOVIMENTO_DOACAO_IDX FOREIGN KEY (ADPET09_ID_USUARIO) REFERENCES ADPET01_USUARIO (ADPET01_ID);


/*############################# TABELA NOTIFICACAO POR HASHTAG*/


-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

-- ALTER TABLE AG02_EMAIL ADD AG02_ID_CONTATO BIGINT
-- ALTER TABLE AG02_EMAIL ADD AG02_DOMINIO VARCHAR (50);
-- ALTER TABLE AG03_TELEFONE ADD CONSTRAINT FK_AG01_ID_CONTATO_EM_EMAIL_IDX FOREIGN KEY (AG03_ID_CONTATO) REFERENCES AG01_CONTATO (AG01_ID);
-- ALTER TABLE AG03_TELEFONE ADD AG03_ID_CONTATO BIGINT
-- ALTER TABLE AG03_TELEFONE ADD CONSTRAINT FK_AG01_ID_CONTATO_EM_TELEFONE_IDX FOREIGN KEY (AG03_ID_CONTATO) REFERENCES AG01_CONTATO (AG01_ID);

-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
