-- MySQL Script generated by MySQL Workbench
-- Thu Aug 15 00:08:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema adota_pet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS adota_pet ;

-- -----------------------------------------------------
-- Schema adota_pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS adota_pet DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE adota_pet ;

-- -----------------------------------------------------
-- Table adota_pet.especie
-- -----------------------------------------------------
DROP TABLE IF EXISTS adota_pet.especie ;

CREATE TABLE IF NOT EXISTS adota_pet.especie (
  especie_id INT(20) NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`especie_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table adota_pet.raca
-- -----------------------------------------------------
DROP TABLE IF EXISTS adota_pet.raca ;

CREATE TABLE IF NOT EXISTS adota_pet.raca (
  raca_id INT(4) NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(200) NULL DEFAULT NULL,
  especie_id INT(4) NOT NULL,
  PRIMARY KEY (`raca_id`, `especie_id`),
  INDEX fk_raca_especie1_idx (`especie_id` ASC) VISIBLE,
  CONSTRAINT fk_raca_especie1
    FOREIGN KEY (`especie_id`)
    REFERENCES adota_pet.especie (`especie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table adota_pet.endereco
-- -----------------------------------------------------
DROP TABLE IF EXISTS adota_pet.endereco ;

CREATE TABLE IF NOT EXISTS adota_pet.endereco (
  endereco_id INT(4) NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(200) NULL DEFAULT NULL,
  bairro VARCHAR(200) NULL DEFAULT NULL,
  cidade VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`endereco_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table adota_pet.usuario
-- -----------------------------------------------------
DROP TABLE IF EXISTS adota_pet.usuario ;

CREATE TABLE IF NOT EXISTS adota_pet.usuario (
  usuario_id INT(4) NOT NULL AUTO_INCREMENT,
  login VARCHAR(200) NOT NULL,
  senha VARCHAR(15) NOT NULL,
  data_lancamento DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ativo TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table adota_pet.cliente
-- -----------------------------------------------------
DROP TABLE IF EXISTS adota_pet.cliente ;

CREATE TABLE IF NOT EXISTS adota_pet.cliente (
  cliente_id INT(4) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(200) NOT NULL,
  cpf VARCHAR(20) NULL DEFAULT NULL,
  cnpj VARCHAR(20) NULL DEFAULT NULL,
  razao_social VARCHAR(200) NULL DEFAULT NULL,
  nome_fantasia VARCHAR(200) NULL DEFAULT NULL,
  data_nascimento DATETIME NULL DEFAULT NULL,
  data_lancamento DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ativo TINYINT(1) NOT NULL,
  usuario_id INT(4) NOT NULL,
  endereco_id INT(4) NOT NULL,
  doador TINYINT(1) NULL DEFAULT NULL,
  telefone VARCHAR(15) NULL,
  email VARCHAR(45) NULL,
  notificar TINYINT(1) NULL,
  PRIMARY KEY (`cliente_id`),
  INDEX fk_cliente_usuario_idx (`usuario_id` ASC) VISIBLE,
  INDEX fk_cliente_endereco1_idx (`endereco_id` ASC) VISIBLE,
  CONSTRAINT fk_cliente_endereco1
    FOREIGN KEY (`endereco_id`)
    REFERENCES adota_pet.endereco (`endereco_id`),
  CONSTRAINT fk_cliente_usuario
    FOREIGN KEY (`usuario_id`)
    REFERENCES adota_pet.usuario (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table adota_pet.animal
-- -----------------------------------------------------
DROP TABLE IF EXISTS adota_pet.animal ;

CREATE TABLE IF NOT EXISTS adota_pet.animal (
  animal_id INT(4) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(200) NULL,
  porte VARCHAR(20) NULL DEFAULT NULL,
  idade INT NULL DEFAULT NULL,
  cor VARCHAR(200) NULL DEFAULT NULL,
  castrado TINYINT(1) NULL,
  sinais VARCHAR(500) NULL DEFAULT NULL,
  descricao VARCHAR(500) NULL DEFAULT NULL,
  data_cadastro DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  adotado TINYINT(1) NULL,
  raca_id INT(4) NOT NULL,
  doador_id INT(4) NULL,
  sexo CHAR(1) NULL,
  ativo TINYINT(1) NULL,
  PRIMARY KEY (`animal_id`),
  INDEX fk_animal_raca1_idx (`raca_id` ASC) VISIBLE,
  INDEX fk_animal_cliente1_idx (`doador_id` ASC) VISIBLE,
  CONSTRAINT fk_animal_raca1
    FOREIGN KEY (`raca_id`)
    REFERENCES adota_pet.raca (`raca_id`),
  CONSTRAINT fk_animal_cliente1
    FOREIGN KEY (`doador_id`)
    REFERENCES adota_pet.cliente (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table adota_pet.lancamento
-- -----------------------------------------------------
DROP TABLE IF EXISTS adota_pet.lancamento ;

CREATE TABLE IF NOT EXISTS adota_pet.lancamento (
  lancamento_id INT(4) NOT NULL AUTO_INCREMENT,
  data_lancamento DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  cliente_id INT(4) NOT NULL,
  PRIMARY KEY (`lancamento_id`),
  INDEX fk_lancamento_acao_cliente1_idx (`cliente_id` ASC) VISIBLE,
  CONSTRAINT fk_lancamento_acao_cliente1
    FOREIGN KEY (`cliente_id`)
    REFERENCES adota_pet.cliente (`cliente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table adota_pet.adocao
-- -----------------------------------------------------
DROP TABLE IF EXISTS adota_pet.adocao ;

CREATE TABLE IF NOT EXISTS adota_pet.adocao (
  adocao_id INT(4) NOT NULL AUTO_INCREMENT,
  lancamento_id INT(4) NOT NULL,
  animal_id INT(4) NOT NULL,
  PRIMARY KEY (`adocao_id`),
  INDEX fk_movimento_adocao_lancamento_acao1_idx (`lancamento_id` ASC) VISIBLE,
  INDEX fk_adocao_animal1_idx (`animal_id` ASC) VISIBLE,
  CONSTRAINT fk_movimento_adocao_lancamento_acao1
    FOREIGN KEY (`lancamento_id`)
    REFERENCES adota_pet.lancamento (`lancamento_id`),
  CONSTRAINT fk_adocao_animal1
    FOREIGN KEY (`animal_id`)
    REFERENCES adota_pet.animal (`animal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;